[package]
name = "echo_server"
version = "0.0.1"
description = "A TCP echo server"
edition = "2024"

[dependencies]
tokio = { version = "1.45.1", features = ["io-util", "net", "macros", "rt"] }
colored = "3.0.0"
